---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-fundamentals
  namespace: jhopman
spec:
  gitImplementation: go-git
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-fundamentals
  timeout: 20s
  url: https://github.com/janhopman-nhb/gitops-fundamentals-exercises

